# Generated by Django 5.1.3 on 2024-11-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('date_of_birth', models.DateField()),
            ],
        ),
    ]
