# Generated by Django 5.1.3 on 2024-11-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
